### PR TITLE
reverse #1

### PR DESCRIPTION
**Pull request by bballboy2002**

### CODE REVIEW

**Comment by MJRLegends** [comment]
Just out of interest how come you are reverting this?

**Comment by bballboy2002** [comment]
I'm trying to figure out how to resolve merge conflicts on my fork before creating a pull on the main repo

**Comment by MJRLegends** [comment]
@bballboy2002 just delete this repository and refork it and what changes did you want to make?

**Comment by bballboy2002** [comment]
I was trying to merge dev_1.7.10 into master but ISSUE_TEMPLATE.md was removed from dev_1.7.10 so that's causing conflict

**Comment by MJRLegends** [comment]
Just delete this repository and refork it

**Comment by bballboy2002** [comment]
The issue occurs on the main repository, so that's why I'm experimenting on here

**Comment by MJRLegends** [comment]
@bballboy2002 i've already fixed it

**Comment by bballboy2002** [comment]
Ok

**Pull request closed without merging**
